import { randomUUID } from 'node:crypto';
import type { IdGenerator } from '../application/ports/organization.repository';

/**
 * Ids are generated by the application, not the database, matching
 * auth-service and users-service. It keeps the domain object complete before
 * it reaches persistence, so a repository is a place to store a row rather
 * than a place where part of it appears.
 */
export class UuidGenerator implements IdGenerator {
  next(): string {
    return randomUUID();
  }
}
